// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: proto/dsr_agent/dsr_agent.proto

package dsr_agent

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageType int32

const (
	MessageType_LOG    MessageType = 0
	MessageType_RESULT MessageType = 1
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "LOG",
		1: "RESULT",
	}
	MessageType_value = map[string]int32{
		"LOG":    0,
		"RESULT": 1,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_dsr_agent_dsr_agent_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_proto_dsr_agent_dsr_agent_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_proto_dsr_agent_dsr_agent_proto_rawDescGZIP(), []int{0}
}

type GRPCMessagePackage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Agent     string      `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
	AgentId   string      `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Data      string      `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Timestamp string      `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Resend    int32       `protobuf:"varint,5,opt,name=resend,proto3" json:"resend,omitempty"`
	Type      MessageType `protobuf:"varint,6,opt,name=type,proto3,enum=dsr_agent.MessageType" json:"type,omitempty"`
}

func (x *GRPCMessagePackage) Reset() {
	*x = GRPCMessagePackage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dsr_agent_dsr_agent_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GRPCMessagePackage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GRPCMessagePackage) ProtoMessage() {}

func (x *GRPCMessagePackage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dsr_agent_dsr_agent_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GRPCMessagePackage.ProtoReflect.Descriptor instead.
func (*GRPCMessagePackage) Descriptor() ([]byte, []int) {
	return file_proto_dsr_agent_dsr_agent_proto_rawDescGZIP(), []int{0}
}

func (x *GRPCMessagePackage) GetAgent() string {
	if x != nil {
		return x.Agent
	}
	return ""
}

func (x *GRPCMessagePackage) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *GRPCMessagePackage) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *GRPCMessagePackage) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *GRPCMessagePackage) GetResend() int32 {
	if x != nil {
		return x.Resend
	}
	return 0
}

func (x *GRPCMessagePackage) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_LOG
}

type ServerReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *ServerReply) Reset() {
	*x = ServerReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dsr_agent_dsr_agent_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerReply) ProtoMessage() {}

func (x *ServerReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dsr_agent_dsr_agent_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerReply.ProtoReflect.Descriptor instead.
func (*ServerReply) Descriptor() ([]byte, []int) {
	return file_proto_dsr_agent_dsr_agent_proto_rawDescGZIP(), []int{1}
}

func (x *ServerReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_dsr_agent_dsr_agent_proto protoreflect.FileDescriptor

var file_proto_dsr_agent_dsr_agent_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x64, 0x73, 0x72, 0x5f, 0x61, 0x67, 0x65, 0x6e,
	0x74, 0x2f, 0x64, 0x73, 0x72, 0x5f, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x09, 0x64, 0x73, 0x72, 0x5f, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x22, 0xbb, 0x01, 0x0a,
	0x12, 0x47, 0x52, 0x50, 0x43, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x50, 0x61, 0x63, 0x6b,
	0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x67, 0x65,
	0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x67, 0x65,
	0x6e, 0x74, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x64,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x64, 0x12, 0x2a,
	0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x64,
	0x73, 0x72, 0x5f, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x27, 0x0a, 0x0b, 0x53, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x2a, 0x22, 0x0a, 0x0b, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x07, 0x0a, 0x03, 0x4c, 0x4f, 0x47, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x52,
	0x45, 0x53, 0x55, 0x4c, 0x54, 0x10, 0x01, 0x32, 0x52, 0x0a, 0x08, 0x44, 0x73, 0x72, 0x41, 0x67,
	0x65, 0x6e, 0x74, 0x12, 0x46, 0x0a, 0x0b, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x12, 0x1d, 0x2e, 0x64, 0x73, 0x72, 0x5f, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x47,
	0x52, 0x50, 0x43, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67,
	0x65, 0x1a, 0x16, 0x2e, 0x64, 0x73, 0x72, 0x5f, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x53, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x2c, 0x5a, 0x2a, 0x61,
	0x6e, 0x71, 0x75, 0x61, 0x63, 0x68, 0x2e, 0x64, 0x65, 0x76, 0x2f, 0x67, 0x6f, 0x2d, 0x61, 0x67,
	0x65, 0x6e, 0x74, 0x2d, 0x73, 0x74, 0x61, 0x73, 0x68, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x64, 0x73, 0x72, 0x5f, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_proto_dsr_agent_dsr_agent_proto_rawDescOnce sync.Once
	file_proto_dsr_agent_dsr_agent_proto_rawDescData = file_proto_dsr_agent_dsr_agent_proto_rawDesc
)

func file_proto_dsr_agent_dsr_agent_proto_rawDescGZIP() []byte {
	file_proto_dsr_agent_dsr_agent_proto_rawDescOnce.Do(func() {
		file_proto_dsr_agent_dsr_agent_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_dsr_agent_dsr_agent_proto_rawDescData)
	})
	return file_proto_dsr_agent_dsr_agent_proto_rawDescData
}

var file_proto_dsr_agent_dsr_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_dsr_agent_dsr_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_dsr_agent_dsr_agent_proto_goTypes = []interface{}{
	(MessageType)(0),           // 0: dsr_agent.MessageType
	(*GRPCMessagePackage)(nil), // 1: dsr_agent.GRPCMessagePackage
	(*ServerReply)(nil),        // 2: dsr_agent.ServerReply
}
var file_proto_dsr_agent_dsr_agent_proto_depIdxs = []int32{
	0, // 0: dsr_agent.GRPCMessagePackage.type:type_name -> dsr_agent.MessageType
	1, // 1: dsr_agent.DsrAgent.SendMessage:input_type -> dsr_agent.GRPCMessagePackage
	2, // 2: dsr_agent.DsrAgent.SendMessage:output_type -> dsr_agent.ServerReply
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_dsr_agent_dsr_agent_proto_init() }
func file_proto_dsr_agent_dsr_agent_proto_init() {
	if File_proto_dsr_agent_dsr_agent_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_dsr_agent_dsr_agent_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GRPCMessagePackage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dsr_agent_dsr_agent_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_dsr_agent_dsr_agent_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_dsr_agent_dsr_agent_proto_goTypes,
		DependencyIndexes: file_proto_dsr_agent_dsr_agent_proto_depIdxs,
		EnumInfos:         file_proto_dsr_agent_dsr_agent_proto_enumTypes,
		MessageInfos:      file_proto_dsr_agent_dsr_agent_proto_msgTypes,
	}.Build()
	File_proto_dsr_agent_dsr_agent_proto = out.File
	file_proto_dsr_agent_dsr_agent_proto_rawDesc = nil
	file_proto_dsr_agent_dsr_agent_proto_goTypes = nil
	file_proto_dsr_agent_dsr_agent_proto_depIdxs = nil
}
