// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.22.3
// source: agent.proto

package agent

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AgentServiceClient is the client API for AgentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AgentServiceClient interface {
	SendSimpleMsgPack(ctx context.Context, in *SimplePackage, opts ...grpc.CallOption) (*ServerReply, error)
	SendLargeMsgPack(ctx context.Context, opts ...grpc.CallOption) (AgentService_SendLargeMsgPackClient, error)
}

type agentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentServiceClient(cc grpc.ClientConnInterface) AgentServiceClient {
	return &agentServiceClient{cc}
}

func (c *agentServiceClient) SendSimpleMsgPack(ctx context.Context, in *SimplePackage, opts ...grpc.CallOption) (*ServerReply, error) {
	out := new(ServerReply)
	err := c.cc.Invoke(ctx, "/agent_service.AgentService/SendSimpleMsgPack", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) SendLargeMsgPack(ctx context.Context, opts ...grpc.CallOption) (AgentService_SendLargeMsgPackClient, error) {
	stream, err := c.cc.NewStream(ctx, &AgentService_ServiceDesc.Streams[0], "/agent_service.AgentService/SendLargeMsgPack", opts...)
	if err != nil {
		return nil, err
	}
	x := &agentServiceSendLargeMsgPackClient{stream}
	return x, nil
}

type AgentService_SendLargeMsgPackClient interface {
	Send(*LargePackage) error
	CloseAndRecv() (*ServerReply, error)
	grpc.ClientStream
}

type agentServiceSendLargeMsgPackClient struct {
	grpc.ClientStream
}

func (x *agentServiceSendLargeMsgPackClient) Send(m *LargePackage) error {
	return x.ClientStream.SendMsg(m)
}

func (x *agentServiceSendLargeMsgPackClient) CloseAndRecv() (*ServerReply, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(ServerReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// AgentServiceServer is the server API for AgentService service.
// All implementations must embed UnimplementedAgentServiceServer
// for forward compatibility
type AgentServiceServer interface {
	SendSimpleMsgPack(context.Context, *SimplePackage) (*ServerReply, error)
	SendLargeMsgPack(AgentService_SendLargeMsgPackServer) error
	mustEmbedUnimplementedAgentServiceServer()
}

// UnimplementedAgentServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAgentServiceServer struct {
}

func (UnimplementedAgentServiceServer) SendSimpleMsgPack(context.Context, *SimplePackage) (*ServerReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendSimpleMsgPack not implemented")
}
func (UnimplementedAgentServiceServer) SendLargeMsgPack(AgentService_SendLargeMsgPackServer) error {
	return status.Errorf(codes.Unimplemented, "method SendLargeMsgPack not implemented")
}
func (UnimplementedAgentServiceServer) mustEmbedUnimplementedAgentServiceServer() {}

// UnsafeAgentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentServiceServer will
// result in compilation errors.
type UnsafeAgentServiceServer interface {
	mustEmbedUnimplementedAgentServiceServer()
}

func RegisterAgentServiceServer(s grpc.ServiceRegistrar, srv AgentServiceServer) {
	s.RegisterService(&AgentService_ServiceDesc, srv)
}

func _AgentService_SendSimpleMsgPack_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SimplePackage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).SendSimpleMsgPack(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/agent_service.AgentService/SendSimpleMsgPack",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).SendSimpleMsgPack(ctx, req.(*SimplePackage))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_SendLargeMsgPack_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentServiceServer).SendLargeMsgPack(&agentServiceSendLargeMsgPackServer{stream})
}

type AgentService_SendLargeMsgPackServer interface {
	SendAndClose(*ServerReply) error
	Recv() (*LargePackage, error)
	grpc.ServerStream
}

type agentServiceSendLargeMsgPackServer struct {
	grpc.ServerStream
}

func (x *agentServiceSendLargeMsgPackServer) SendAndClose(m *ServerReply) error {
	return x.ServerStream.SendMsg(m)
}

func (x *agentServiceSendLargeMsgPackServer) Recv() (*LargePackage, error) {
	m := new(LargePackage)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// AgentService_ServiceDesc is the grpc.ServiceDesc for AgentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agent_service.AgentService",
	HandlerType: (*AgentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendSimpleMsgPack",
			Handler:    _AgentService_SendSimpleMsgPack_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SendLargeMsgPack",
			Handler:       _AgentService_SendLargeMsgPack_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "agent.proto",
}
